server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    autoindex off;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|mjs|json|css)$ {
        expires -1;
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }
}
