#!/usr/bin/env python3
"""Write src/buildInfo.js from the current git revision (gitignored)."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

WEBAPP = Path(__file__).resolve().parent
REPO = WEBAPP.parent
OUT = WEBAPP / "src" / "buildInfo.js"


def _git(*args: str) -> str | None:
    try:
        return subprocess.check_output(
            ["git", *args],
            cwd=REPO,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return None


def write_build_info(commit: str | None = None) -> str:
    """Write buildInfo.js and return the displayed commit string."""
    if commit:
        display = commit.strip() or "unknown"
    else:
        short = _git("rev-parse", "--short=7", "HEAD") or "unknown"
        dirty = False
        if short != "unknown":
            status = _git("status", "--porcelain")
            dirty = bool(status)
        display = f"{short}+" if dirty else short

    OUT.write_text(
        "// Generated by write_build_info.py — do not edit.\n"
        f'export const BUILD_COMMIT = "{display}";\n',
        encoding="utf-8",
    )
    return display


def main() -> int:
    override = sys.argv[1] if len(sys.argv) > 1 else None
    print(write_build_info(override))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
